### PR TITLE
done. also added some styling

### PR DESCRIPTION
**Pull request by jzakaria**
#98

### CODE REVIEW

**Comment by jharriman** [comment]
Does this resolve #98?

**Comment by jzakaria** [comment]
there's still the 400 being returned instead of the 409. Also, are topic names case-sensitive?

**Comment by jharriman** [comment]
Topic names should be case-sensitive, will have to check though.

**Comment by jharriman** [comment]
#103 should fix #98, merging your clientside change now @jzakaria

**Pull request merged**
